import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { requireSession } from "@/lib/auth/session";
import { GroupRepository } from "@/lib/repositories/group-repository";
import { MemberRepository } from "@/lib/repositories/member-repository";

export default async function GroupsPage() { const session = await requireSession(); const [groups, members] = await Promise.all([new GroupRepository().list(), new MemberRepository().listSafe()]); return <AppShell session={session}><main className="mx-auto w-full max-w-7xl px-5 py-10 md:px-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Shared parent posts</p><h1 className="mt-2 text-3xl font-semibold">Groups</h1><p className="mt-3 text-sm text-muted-foreground">Teams target và parent schedule dùng chung.</p></div><div className="flex w-full gap-2 sm:w-auto"><Button nativeButton={false} render={<Link href="/me/group" />} variant="outline" className="flex-1 sm:flex-none">Group của tôi</Button><Button nativeButton={false} render={<Link href="/groups/new" />} className="flex-1 sm:flex-none">Tạo group</Button></div></div><div className="grid gap-4 lg:grid-cols-2">{groups.map((group) => { const count = members.filter((member) => member.groupId === group.id).length; return <Card key={group.id}><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-semibold">{group.name}</h2><p className="mt-1 break-all text-xs text-muted-foreground">{group.id}</p></div><Badge variant={group.enabled ? "default" : "secondary"}>{group.enabled ? "Hoạt động" : "Đã tắt"}</Badge></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Info label="Thành viên" value={String(count)} /><Info label="Giờ parent" value={group.parentPost.postAfterTime} /><Info label="Timezone" value={group.parentPost.timezone} /><Info label="Version" value={String(group.version)} /></div><div className="mt-5 border-t pt-4"><Button nativeButton={false} render={<Link href={`/groups/${group.id}/edit`} />} variant="outline" size="sm">Xem / chỉnh sửa</Button></div></CardContent></Card>; })}</div></main></AppShell>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 truncate font-medium">{value}</p></div>; }
